### ISSUE TITLE
Error: Can't load project demo ("TypeError [ERR_INVALID_ARG_TYPE]")

### ISSUE THREAD

**Issue by liamCorbett** [productioncoder/youtube-react#3]
Following the instructions in the readme as-is produced an error when trying to launch the app in any browser. 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at noopServiceWorkerMiddleware (C:\Users\Liam\Desktop\youtube-react-master\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Users\Liam\Desktop\youtube-react-master\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\Users\Liam\Desktop\youtube-react-master\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\Users\Liam\Desktop\youtube-react-master\node_modules\express\lib\router\layer.js:95:5)
```

Bumping react-scripts from 3.3.0 to 3.4.0 solved the problem, per https://stackoverflow.com/questions/58199001/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re

**Comment by productioncoder** [comment]
Hi @liamCorbett 

first of all sry. for my late reply and thanks for pointing out the issue.
I just updated all outdated `npm` dependencies and bumped `react-scripts` to `3.4.0`.

So should work again 😁

Please let me know if you experience any other issues - otherwise I would just close this one.

Best,

Jan

**Comment by liamCorbett** [comment]
Beautiful, thanks man!
